Config = Config or {}

Config.Dev = false
Config.lang = 'da'

Config.Items = {
    ['coke'] = {
        type = 'farm',
        label = 'Kokain',
        processedItem = 'posekokain',
        processAmount = 8,
        processRequires = { ['coke'] = 16 },
        farmAmount = 8,
        farmTime = 10500,
        scenario = 'WORLD_HUMAN_GARDENER_PLANT',
        icon = 'fa-solid fa-leaf',
        iconColor = '#ffffff',
        animDict = nil,
        animName = nil,
    },
    ['meth'] = {
        type = 'farm',
        label = 'Amfetamin',
        processedItem = 'posemeth',
        processAmount = 8,
        processRequires = { ['meth'] = 16 },
        farmAmount = 8,
        farmTime = 10500,
        scenario = 'WORLD_HUMAN_GARDENER_PLANT',
        icon = 'fa-solid fa-flask',
        iconColor = '#87ceeb',
        animDict = nil,
        animName = nil,
    },
    ['opium'] = {
        type = 'farm',
        label = 'Opium',
        processedItem = 'opium_pooch',
        processAmount = 8,
        processRequires = { ['opium'] = 16 },
        farmAmount = 8,
        farmTime = 10500,
        scenario = 'WORLD_HUMAN_GARDENER_PLANT',
        icon = 'fa-solid fa-flower',
        iconColor = '#E35335',
        animDict = nil,
        animName = nil,
    },
    ['weed'] = {
        type = 'farm',
        label = 'Cannabis',
        processedItem = 'weed_pooch',
        processAmount = 8,
        processRequires = { ['weed'] = 16 },
        farmAmount = 8,
        farmTime = 10500,
        scenario = nil,
        icon = 'fa-solid fa-leaf',
        iconColor = '#22c55e',
        animDict = 'amb@prop_human_parking_meter@male@base',
        animName = 'base',
    },
    ['svampe'] = {
        type = 'farm',
        label = 'Svampe',
        processedItem = nil,
        processAmount = nil,
        processRequires = nil,
        farmAmount = 8,
        farmTime = 10500,
        scenario = 'WORLD_HUMAN_GARDENER_PLANT',
        icon = 'fa-solid fa-plant-wilt',
        iconColor = '#ba9e88',
        animDict = nil,
        animName = nil,
    },
    ['posekokain'] = {
        type = 'process',
        label = 'Pose Kokain',
        processRequires = { ['coke'] = 16 },
        processAmount = 8,
        processTime = 10500,
        icon = 'fa-solid fa-box',
        iconColor = '#ffffff',
        animDict = 'amb@prop_human_parking_meter@male@base',
        animName = 'base',
    },
    ['posemeth'] = {
        type = 'process',
        label = 'Pose Amfetamin',
        processRequires = { ['meth'] = 16 },
        processAmount = 8,
        processTime = 10500,
        icon = 'fa-solid fa-box',
        iconColor = '#00d8f5',
        animDict = 'amb@prop_human_parking_meter@male@base',
        animName = 'base',
    },
    ['opium_pooch'] = {
        type = 'process',
        label = 'Pose Opium',
        processRequires = { ['opium'] = 16 },
        processAmount = 8,
        processTime = 10500,
        icon = 'fa-solid fa-box',
        iconColor = '#8b4513',
        animDict = 'amb@prop_human_parking_meter@male@base',
        animName = 'base',
    },
    ['weed_pooch'] = {
        type = 'process',
        label = 'Pose Cannabis',
        processRequires = { ['weed'] = 16 },
        processAmount = 8,
        processTime = 10500,
        icon = 'fa-solid fa-box',
        iconColor = '#22c55e',
        animDict = 'amb@prop_human_parking_meter@male@base',
        animName = 'base',
    },
}